### ISSUE TITLE
Make compatible with Browserify

### ISSUE THREAD

**Issue by morgante** [somespider/allbases#5]
We need to be able to generate IDs client-side, so can we make this compatible with Browserify?

Currently, trying to call it via ```shareId = allbases.randomBase62(10);``` generates this error:
```
Uncaught TypeError: rand is not a function
    at genRandom (http://lcl.cafe.com:48830/mergedAssets.js:397:12)
    at random (http://lcl.cafe.com:48830/mergedAssets.js:434:9)
    at Object.module.exports.randomBase62 (http://lcl.cafe.com:48830/mergedAssets.js:456:46)
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:10)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)
    at Object.module.exports.attach (http://lcl.cafe.com:48830/mergedAssets.js:28320:5)
    at module.exports.BaseApp.extend.initialize (http://lcl.cafe.com:48830/mergedAssets.js:26930:14)
    at Backbone.Model (http://lcl.cafe.com:48830/mergedAssets.js:57949:21)
```

**Comment by efuquen** [comment]
Hmm, i'll have to test it again but I already did work to make this work on the client-side.  something might have broken.

**Comment by efuquen** [comment]
I updated to work on older browserify versions missing the pseudoRandomBytes function.
